# Generated by Django 3.0.2 on 2020-01-23 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=200, verbose_name='回答内容')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
            options={
                'verbose_name': '学生回答',
                'verbose_name_plural': '学生回答',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='answers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.Answer'),
        ),
    ]
