# Generated by Django 3.0.2 on 2020-01-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20200130_2110'),
        ('students', '0003_auto_20200124_1629'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_sn', 'exam')},
        ),
    ]
