# Generated by Django 3.0.2 on 2020-02-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200131_1937'),
        ('students', '0004_auto_20200131_1937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('student', 'question')},
        ),
    ]
