# Generated by Django 3.0.2 on 2020-02-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200201_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=-1.0, max_length=3, verbose_name='得分'),
        ),
    ]
