# Generated by Django 3.0.2 on 2020-02-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200201_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
