# Generated by Django 3.0.2 on 2020-01-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200129_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.IntegerField(choices=[(1, '英文'), (2, '中文')], default=1, verbose_name='语言类型'),
        ),
        migrations.AddField(
            model_name='question',
            name='refs',
            field=models.TextField(default='', help_text="若有多个参考答案用'/'隔开", max_length=200, verbose_name='参考答案'),
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
