# Generated by Django 3.0.2 on 2020-01-31 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20200130_2110'),
        ('questions', '0004_auto_20200130_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.Examination', verbose_name='所属考试'),
        ),
    ]
