# Generated by Django 3.0.2 on 2020-02-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20200130_2110'),
        ('questions', '0005_auto_20200131_1937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_no', 'exam')},
        ),
    ]
