# Generated by Django 3.0.2 on 2020-02-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200201_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_no',
            field=models.CharField(max_length=3, verbose_name='题号'),
        ),
    ]
