# Generated by Django 3.0.2 on 2020-01-22 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.IntegerField(choices=[(1, '英文'), (2, '中文')], default=1, verbose_name='语言类型')),
                ('text', models.TextField(default='', max_length=200, verbose_name='文本内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '参考答案',
                'verbose_name_plural': '参考答案',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.CharField(max_length=3, verbose_name='题号')),
                ('question_type', models.IntegerField(choices=[(1, '填空题'), (2, '改错题'), (3, '翻译题'), (4, '简答题')], default=1, help_text='问题类型：1(填空),2(改错),3(翻译),4(简答)', verbose_name='问题类型')),
                ('full_score', models.FloatField(max_length=3, verbose_name='满分值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('references', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Reference')),
            ],
            options={
                'verbose_name': '题目信息',
                'verbose_name_plural': '题目信息',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_time', models.DateTimeField(verbose_name='考试时间（年/月）')),
                ('exam_name', models.CharField(max_length=20, verbose_name='考试名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Question')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'verbose_name': '考试信息',
                'verbose_name_plural': '考试信息',
            },
        ),
    ]
