# Generated by Django 3.0.2 on 2020-01-24 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='students',
        ),
        migrations.AlterField(
            model_name='examination',
            name='exam_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='考试时间（年/月）'),
        ),
    ]
