# Generated by Django 3.0.2 on 2020-01-29 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200129_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='exam_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 13, 21, 40, 743016, tzinfo=utc), verbose_name='考试时间（年/月）'),
        ),
    ]
