# Generated by Django 3.0.2 on 2020-01-23 08:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0002_auto_20200123_1659'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('score', models.FloatField(default=0, verbose_name='分数值')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Examination')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'verbose_name': '分数信息',
                'verbose_name_plural': '分数信息',
            },
        ),
    ]
